"""Initial UUID schema

Revision ID: d6c7d64596b3
Revises: 
Create Date: 2025-03-21 20:24:40.199574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c7d64596b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('memory_pyramids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['base_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pyramid_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pyramid_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pyramid_id'], ['memory_pyramids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pyramid_id', 'level', name='_pyramid_level_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyramid_levels')
    op.drop_table('memory_pyramids')
    op.drop_table('prompt_templates')
    op.drop_table('base_memories')
    # ### end Alembic commands ###
